---
# User defined
Species: "Mus musculus"  # Mus musculus or Homo sapiens
Spikein: "Amp"  # Amp or Bacteria
PicardLoc:
SEACRLoc:
bowtie2_index: # download from iGenomes








# Defined
sample_info: ./config/Samplesheet.tsv
Spike_align: "-p 8 --end-to-end --very-sensitive --no-overlap --no-dovetail --no-mixed --no-discordant --phred33 -I 10 -X 700"
bamCov_default: "--binSize 10 --ignoreForNormalization 'chrM' --extendReads"
bamCov_min: "--binSize 10 --extendReads"
bamCov_CPM: "--binSize 10  --normalizeUsing 'CPM' --ignoreForNormalization 'chrM' --extendReads"
genome_align: "-p 8 --local --very-sensitive-local --no-unal --no-mixed --no-discordant --phred33 -I 10 -X 700"
samtools_mapq: "-q 10"
samtools_proper_paired: "-f 2"




# Spikein
Spikein_index_amp: ./Reference_files/Spikein_indices/Amp_pbluescript/Amp_index/Amp_pBlue
Spikein_index_Ecoli:  ./Reference_files/Spikein_indices/EcoliK12_index/EcoliK12Index/EcoliK12
